---
name: Link check

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lychee.toml README.md template/README.md
          fail: true
