---
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'push' && 'main' || github.event.pull_request.head.ref }}

      - uses: pre-commit/action@v3.0.1
